// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfxsiryjmkkpiageesfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmeHNpcnlqbWtrcGlhZ2Vlc2ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2ODI4NTgsImV4cCI6MjA2ODI1ODg1OH0.3J1FWrJEI2V5CIBjYBgCMcKVjGjLg3iyTyraH4A3K2c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});